### ISSUE TITLE
start_test produces weird error

### ISSUE THREAD

**Issue by buddha314** [marcoscleison/chrest#4]
Main file in `../src/`

```chapel
use Chrest,
    ChrestRouter;

config const API_HOST: string,
             API_PORT: int;

proc main() {
  var srv = new Chrest(API_HOST, API_PORT);
  srv.Listen();
  srv.Close();
}
```

And the test file in `../test/`

```chapel
use Apiyatollah,
    Curl,
    Spawn;

var sub = spawn(["..bin/apiyatollah"], stdout=PIPE);
```

produces this error

```
In file included from /var/folders/g5/4zwyfk513hd94tjs1fm5mdq00000gn/T//chpl-buddha-7252.deleteme/_main.c:2:
In file included from /var/folders/g5/4zwyfk513hd94tjs1fm5mdq00000gn/T//chpl-buddha-7252.deleteme/chpl__header.h:11:
/Users/buddha/github/buddha314/chrest/src/chrest.h:28:5: error: no previous prototype for function 'get_port_from_request' [-Werror,-Wmissing-prototypes]
int get_port_from_request(){
    ^
1 error generated.
```

This was originally filed in the wrong repo: https://github.com/marcoscleison/chapel-http/issues/1

**Comment by marcoscleison** [comment]
This issue is related with some files utils coded in C. I removed the files because I can everything in Chapel.
I pushed it now. Please test the server example:
https://github.com/marcoscleison/chrest/blob/27a57f66f4f8590e8cd48a57e4247ed4fa383041/examples/srv.chpl#L126
With the client example:
https://github.com/marcoscleison/chrest/blob/27a57f66f4f8590e8cd48a57e4247ed4fa383041/examples/cli.chpl#L19
